/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jsqix_yunpos_app_utils_UAD */

#ifndef _Included_com_jsqix_yunpos_app_utils_UAD
#define _Included_com_jsqix_yunpos_app_utils_UAD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jsqix_yunpos_app_utils_UAD
 * Method:    getParaMd5Key
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jsqix_yunpos_app_utils_UAD_getParaMd5Key(
		JNIEnv* env, jobject obj) {
	return (*env)->NewStringUTF(env, "1732e45564733ae7eb7b7175eda16071");
}

/*
 * Class:     com_jsqix_yunpos_app_utils_UAD
 * Method:    getPswMd5Key
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jsqix_yunpos_app_utils_UAD_getPswMd5Key(
		JNIEnv* env, jobject obj) {
	return (*env)->NewStringUTF(env, "4a3ba9c3e6bb7d38ca0270050de8dab9");
}

/*
 * Class:     com_jsqix_yunpos_app_utils_UAD
 * Method:    getRequestIp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jsqix_yunpos_app_utils_UAD_getRequestIp(
		JNIEnv* env, jobject obj) {
	return (*env)->NewStringUTF(env, "http://120.55.191.214/api/");
}

#ifdef __cplusplus
}
#endif
#endif
