/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jsqix_yunpos_app_utils_UAD */

#ifndef _Included_com_jsqix_yunpos_app_utils_UAD
#define _Included_com_jsqix_yunpos_app_utils_UAD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jsqix_yunpos_app_utils_UAD
 * Method:    getParaMd5Key
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jsqix_yunpos_app_utils_UAD_getParaMd5Key
  (JNIEnv *, jclass);

/*
 * Class:     com_jsqix_yunpos_app_utils_UAD
 * Method:    getPswMd5Key
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jsqix_yunpos_app_utils_UAD_getPswMd5Key
  (JNIEnv *, jclass);

/*
 * Class:     com_jsqix_yunpos_app_utils_UAD
 * Method:    getRequestIp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jsqix_yunpos_app_utils_UAD_getRequestIp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
